"""Type stubs for the agentwerk Python bindings."""

from typing import Any, Awaitable, Callable, Optional, overload

class Provider:
    """An LLM provider, passed to ``Agent.provider(...)``."""

class Model:
    """A model name, with an optional context window size and reasoning level."""

    def __init__(self, name: str) -> None: ...
    def context_window(self, size: int) -> "Model": ...
    def reasoning_effort(self, effort: str) -> "Model": ...
    def get_context_window(self) -> Optional[int]: ...
    def get_reasoning_effort(self) -> str: ...

def provider_from_env() -> Provider:
    """Read the LLM provider from environment variables."""

def model_from_env() -> str:
    """Read the model name from environment variables."""

def context_window_from_env() -> Optional[int]:
    """Read the context window size from ``MODEL_CONTEXT_WINDOW``, or ``None``."""

def AnthropicProvider(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def OpenAiProvider(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def MistralProvider(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def LiteLlmProvider(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...

class Tool:
    """A tool an agent may call, passed to ``Agent.tool(...)``."""

class ToolResult:
    """What a tool reports back when a bare return value is not enough."""

    @staticmethod
    def success(content: str) -> "ToolResult": ...
    @staticmethod
    def error(content: str) -> "ToolResult": ...
    @staticmethod
    def schema_error(content: str) -> "ToolResult": ...

def ReadFileTool() -> Tool: ...
def WriteFileTool() -> Tool: ...
def EditFileTool() -> Tool: ...
def GrepTool() -> Tool:
    """Search file contents by regular expression, or by code shape with ``syntax="code"``."""
    ...
def GlobTool() -> Tool: ...
def ListDirectoryTool() -> Tool: ...
def FetchUrlTool() -> Tool: ...
def FindToolsTool() -> Tool: ...
def ManageKnowledgeTool(store: "Knowledge") -> Tool: ...
def ReadTicketsTool() -> Tool: ...
def ManageTicketsTool() -> Tool: ...
def FinishTool() -> Tool: ...
def BashTool(
    name: str,
    pattern: str,
    description: Optional[str] = ...,
    read_only: bool = ...,
) -> Tool: ...
def UnrestrictedBashTool() -> Tool: ...

@overload
def tool(func: Callable[..., Any]) -> Callable[..., Any]: ...
@overload
def tool(
    *,
    read_only: bool = ...,
    defer: bool = ...,
    paths: Optional[list[str]] = ...,
    schema: Optional[dict] = ...,
    name: Optional[str] = ...,
    description: Optional[str] = ...,
) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class Schema:
    def __init__(self, document: Any) -> None: ...
    def validate(self, value: Any) -> Any: ...

class ReplyContent:
    """One block inside a reply: text, a tool call, a tool result, or reasoning."""

    kind: str
    data: dict

    @staticmethod
    def text(text: str) -> "ReplyContent": ...
    @staticmethod
    def tool_use(id: str, name: str, input: Any) -> "ReplyContent": ...
    @staticmethod
    def tool_result(
        tool_use_id: str,
        content: str,
        succeeded: bool = ...,
        path: Optional[str] = ...,
    ) -> "ReplyContent": ...
    @staticmethod
    def thinking(thinking: str, signature: str) -> "ReplyContent": ...
    @staticmethod
    def redacted_thinking(data: str) -> "ReplyContent": ...
    def __repr__(self) -> str: ...

class Reply:
    """One entry in a ticket's replies."""

    author: str
    content: list[ReplyContent]
    created_at: int

    @staticmethod
    def user_text(text: str) -> "Reply": ...
    def __repr__(self) -> str: ...

class Ticket:
    key: str
    status: str
    task: Any
    result: Optional[Any]
    labels: list[str]
    schema: Optional[Schema]
    parent: Optional[str]
    reporter: str
    created_at: int
    started_at: Optional[int]
    finished_at: Optional[int]
    failed_at: Optional[int]
    replies: list[Reply]

    def __init__(
        self,
        task: Any,
        *,
        labels: Optional[list[str]] = ...,
        schema: Optional[Schema] = ...,
        parent: Optional[str] = ...,
    ) -> None: ...
    def has_label(self, label: str) -> bool: ...
    def is_todo(self) -> bool: ...
    def is_finished(self) -> bool: ...
    def is_failed(self) -> bool: ...
    def is_in_progress(self) -> bool: ...
    def is_pending(self) -> bool: ...
    def is_resolved(self) -> bool: ...
    def __repr__(self) -> str: ...

class Compaction:
    def reason(self) -> str: ...
    def ticket(self) -> Ticket: ...
    def window(self) -> Optional[int]: ...
    async def summarize(self, replies: list[Reply]) -> str: ...

class Trajectory:
    key: str
    model: Optional[str]
    replies: list[Reply]

    @staticmethod
    def from_ticket(
        agent: str, model: Optional[str], ticket: Ticket
    ) -> "Trajectory": ...
    def save(self, dir: str) -> None: ...
    def __repr__(self) -> str: ...

class Page:
    slug: str
    kind: str
    description: str
    content: str
    tags: list[str]

    def __init__(
        self,
        slug: str,
        description: str,
        content: str,
        kind: str = ...,
        tags: Optional[list[str]] = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Pages:
    def save(self, page: Page) -> None: ...
    def load(self, slug: str) -> Page: ...
    def list(self) -> list[Page]: ...
    def remove(self, slug: str) -> None: ...

class Knowledge:
    @staticmethod
    def load(dir: str) -> "Knowledge": ...
    def index_char_limit(self, n: int) -> "Knowledge": ...
    def get_index_char_limit(self) -> int: ...
    def index(self) -> str: ...
    def pages(self) -> Pages: ...
    def clear(self) -> None: ...

class Event:
    kind: str
    agent_name: str
    ticket_key: str
    @property
    def data(self) -> dict: ...
    def __repr__(self) -> str: ...

class EventName:
    """Every event kind's name, the spelling `Event.kind` reports."""

    RUN_STARTED: str
    RUN_FINISHED: str
    TICKET_CREATED: str
    TICKET_STARTED: str
    TICKET_FINISHED: str
    TICKET_FAILED: str
    TURN_STARTED: str
    REQUEST_STARTED: str
    REQUEST_FINISHED: str
    REQUEST_FAILED: str
    REQUEST_RETRIED: str
    TEXT_CHUNK_RECEIVED: str
    TOOL_CALL_STARTED: str
    TOOL_CALL_FINISHED: str
    TOOL_CALL_FAILED: str
    FILE_OPEN_FINISHED: str
    FILE_OPEN_FAILED: str
    KNOWLEDGE_USED: str
    KNOWLEDGE_FAILED: str
    POLICY_VIOLATED: str
    SCHEMA_RETRIED: str
    COMPACTION_STARTED: str
    COMPACTION_PROGRESS: str
    COMPACTION_FINISHED: str
    COMPACTION_FAILED: str

class TimeStat:
    total: float
    average: Optional[float]

    def __repr__(self) -> str: ...

class ToolStat:
    calls: int
    not_found: int
    execution_failed: int
    schema_failed: int

    def errors(self) -> int: ...
    def error_rate(self) -> Optional[float]: ...
    def __repr__(self) -> str: ...

class FileStat:
    opens: int
    failed: int

    def errors(self) -> int: ...
    def error_rate(self) -> Optional[float]: ...
    def __repr__(self) -> str: ...

class KnowledgeStat:
    attempts: int
    failed: int

    def errors(self) -> int: ...
    def error_rate(self) -> Optional[float]: ...
    def __repr__(self) -> str: ...

class ModelStat:
    requests: int
    failed: int
    input_tokens: int
    output_tokens: int

    def errors(self) -> int: ...
    def error_rate(self) -> Optional[float]: ...
    def __repr__(self) -> str: ...

class Stats:
    """The metrics about tickets, tokens, and time, for the whole execution or for
    one label or agent within it. Every duration is in seconds."""

    def stats_for_label(self, label: str) -> "Stats": ...
    def stats_for_agent(self, agent_name: str) -> "Stats": ...
    def tool_stats(self) -> dict[str, ToolStat]: ...
    def file_stats(self) -> dict[str, FileStat]: ...
    def knowledge_stats(self) -> dict[str, KnowledgeStat]: ...
    def model_stats(self) -> dict[str, ModelStat]: ...
    def event_count(self, name: str) -> int: ...
    def event_counts(self) -> dict[str, int]: ...
    def input_tokens(self) -> int: ...
    def output_tokens(self) -> int: ...
    def execution_duration(self) -> Optional[float]: ...
    def ticket_duration(self) -> TimeStat: ...
    def agent_duration(self) -> TimeStat: ...
    def to_dict(self) -> dict: ...
    def __repr__(self) -> str: ...

class Agent:
    """The core entity of agentwerk. It has access to tools for solving tasks in
    the form of tickets."""

    def __init__(self) -> None: ...
    @staticmethod
    def empty() -> "Agent": ...
    def from_env(self) -> "Agent": ...
    def provider_from_env(self) -> "Agent": ...
    def provider(self, provider: Provider) -> "Agent": ...
    def model(self, model: "str | Model") -> "Agent": ...
    def model_from_env(self) -> "Agent": ...
    def name(self, name: str) -> "Agent": ...
    def role(self, role: str) -> "Agent": ...
    def label(self, label: str) -> "Agent": ...
    def labels(self, labels: list[str]) -> "Agent": ...
    def interactive(self) -> "Agent": ...
    def template(self, key: str, value: str) -> "Agent": ...
    def templates(self, variables: dict[str, str]) -> "Agent": ...
    def dir(self, dir: str) -> "Agent": ...
    def knowledge(self, store: Knowledge) -> "Agent": ...
    def tool(self, tool: Any) -> "Agent": ...
    def tools(self, tools: list) -> "Agent": ...
    def edit_directive_on_retry(
        self, editor: Callable[[str, str], Optional[str]]
    ) -> "Agent": ...
    def build(self) -> "Agent": ...
    def task(self, task: Any) -> str: ...
    def ticket(self, ticket: Ticket) -> str: ...
    def ticket_queue(self, queue: "TicketQueue") -> "Agent": ...
    def start(self) -> "TicketQueue": ...
    async def finish(self) -> "TicketQueue": ...

class TicketQueue:
    def __init__(self) -> None: ...
    @staticmethod
    def load(dir: str) -> "TicketQueue": ...
    def agent(self, agent: Agent) -> "TicketQueue": ...
    def task(self, task: Any) -> str: ...
    def ticket(self, ticket: Ticket) -> str: ...
    def reply(self, key: str, content: str) -> "TicketQueue": ...
    def set_finished(self, key: str, result: Any) -> None: ...
    def set_failed(self, key: str) -> None: ...
    def max_turns(self, n: int) -> "TicketQueue": ...
    def max_input_tokens(self, n: int) -> "TicketQueue": ...
    def max_output_tokens(self, n: int) -> "TicketQueue": ...
    def max_request_tokens(self, n: int) -> "TicketQueue": ...
    def max_schema_retries(self, n: int) -> "TicketQueue": ...
    def max_request_retries(self, n: int) -> "TicketQueue": ...
    def max_time(self, seconds: float) -> "TicketQueue": ...
    def request_retry_delay(self, seconds: float) -> "TicketQueue": ...
    def compact_at(self, fraction: float) -> "TicketQueue": ...
    def get_max_turns(self) -> Optional[int]: ...
    def get_max_input_tokens(self) -> Optional[int]: ...
    def get_max_output_tokens(self) -> Optional[int]: ...
    def get_max_request_tokens(self) -> Optional[int]: ...
    def get_max_schema_retries(self) -> Optional[int]: ...
    def get_max_request_retries(self) -> int: ...
    def get_max_time(self) -> Optional[float]: ...
    def get_request_retry_delay(self) -> float: ...
    def get_compact_at(self) -> Optional[float]: ...
    def dir(self, dir: str) -> "TicketQueue": ...
    def get_dir(self) -> str: ...
    def schema_for_label(self, label: str, schema: Schema) -> "TicketQueue": ...
    def on_event(self, callback: Callable[[Event], Any]) -> "TicketQueue": ...
    def on_result(
        self, callback: Callable[[Ticket, Any], Any]
    ) -> "TicketQueue": ...
    def on_failure(
        self, callback: Callable[[Event, Ticket], Any]
    ) -> "TicketQueue": ...
    def cancel_on_event(self, predicate: Callable[[Event], bool]) -> "TicketQueue": ...
    def cancel_on_result(
        self, predicate: Callable[[Ticket, Any], bool]
    ) -> "TicketQueue": ...
    def cancel_on_failure(
        self, predicate: Callable[[Event, Ticket], bool]
    ) -> "TicketQueue": ...
    def cancel_on(self, awaitable: Awaitable[Any]) -> "TicketQueue": ...
    def create_ticket_on_event(
        self, make: Callable[[Event], Optional[Ticket]]
    ) -> "TicketQueue": ...
    def create_ticket_on_result(
        self, make: Callable[[Ticket, Any], Optional[Ticket]]
    ) -> "TicketQueue": ...
    def create_ticket_on_failure(
        self, make: Callable[[Event, Ticket], Optional[Ticket]]
    ) -> "TicketQueue": ...
    def on_ticket(
        self, callback: Callable[[Event, Ticket], Any]
    ) -> "TicketQueue": ...
    def edit_replies_on_event(
        self, editor: Callable[[list[Event], list[Reply]], Optional[list[Reply]]]
    ) -> "TicketQueue": ...
    def edit_replies_on_compaction(
        self,
        editor: Callable[["Compaction", list[Reply]], Any],
    ) -> "TicketQueue": ...
    def edit_replies(
        self, key: str, editor: Callable[[list[Reply]], Optional[list[Reply]]]
    ) -> "TicketQueue": ...
    def cancel_label(self, label: str) -> "TicketQueue": ...
    def label_cancelled(self, label: str) -> bool: ...
    def cancel_label_on_event(
        self, label: str, predicate: Callable[[Event], bool]
    ) -> "TicketQueue": ...
    def cancel_label_on_result(
        self, label: str, predicate: Callable[[Ticket, Any], bool]
    ) -> "TicketQueue": ...
    def cancel_label_on_failure(
        self, label: str, predicate: Callable[[Event, Ticket], bool]
    ) -> "TicketQueue": ...
    def model_for_agent(self, agent_name: str) -> Optional[str]: ...
    def get_ticket(self, key: str) -> Optional[Ticket]: ...
    def tickets(self) -> list[Ticket]: ...
    def tickets_for_label(self, label: str) -> list[Ticket]: ...
    def find_tickets(self, predicate: Callable[[Ticket], bool]) -> list[Ticket]: ...
    def find_ticket(self, predicate: Callable[[Ticket], bool]) -> Optional[Ticket]: ...
    async def wait_for_ticket(
        self, predicate: Callable[[Ticket], bool]
    ) -> Optional[Ticket]: ...
    def start(self) -> "TicketQueue": ...
    async def finish(self) -> "TicketQueue": ...
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...
    def finish_reason(self) -> Optional[str]: ...
    def stats(self) -> Stats: ...
    def last_result(self) -> Optional[Any]: ...
    def results(self) -> list[Any]: ...
    def results_for_label(self, label: str) -> list[Any]: ...
