"""Type stubs for the agentwerk Python bindings."""

import os
from typing import Any, Awaitable, Callable, Optional, overload

class Provider:
    """An LLM provider, passed to ``Agent.provider(...)``."""

    @staticmethod
    def from_env() -> "Provider": ...

class Model:
    """A model name, with an optional context window size and reasoning level."""

    def __init__(self, name: str) -> None: ...
    @staticmethod
    def from_env() -> "Model": ...
    def context_window(self, size: int) -> "Model": ...
    def reasoning_effort(self, effort: str) -> "Model": ...
    def get_name(self) -> str: ...
    def get_context_window(self) -> Optional[int]: ...
    def get_reasoning_effort(self) -> str: ...

def Anthropic(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def OpenAi(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def Mistral(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...
def LiteLlm(
    api_key: str, base_url: Optional[str] = ..., timeout: Optional[float] = ...
) -> Provider: ...

class Tool:
    """A tool an agent may call, passed to ``Agent.tool(...)``."""

def ReadFileTool() -> Tool: ...
def WriteFileTool() -> Tool: ...
def EditFileTool() -> Tool: ...
def GrepTool() -> Tool:
    """Search file contents by regular expression, or by code shape with ``syntax="code"``."""
    ...
def GlobTool() -> Tool: ...
def ListDirectoryTool() -> Tool: ...
def KnowledgeTool(store: "Knowledge") -> Tool: ...
def TasksTool() -> Tool: ...
def FinishTool() -> Tool: ...

class FetchUrlTool:
    """Fetch a URL and read its body, passed to ``Agent.tool(...)``."""

    def __init__(self) -> None: ...
    def impersonate(self) -> "FetchUrlTool":
        """Send the headers and HTTP/2 settings a browser sends. The TLS
        handshake is unchanged, so a site reading the ClientHello rather than
        the headers refuses the request either way."""
        ...

class CommandTool:
    """A command an agent may call, passed to ``Agent.tool(...)``."""

    def __init__(self, name: str) -> None: ...
    def allow(self, pattern: str) -> "CommandTool": ...
    def allow_flag(self, flag: str) -> "CommandTool": ...
    def deny(self, pattern: str) -> "CommandTool": ...
    def deny_flag(self, flag: str) -> "CommandTool": ...
    def description(self, description: "str | os.PathLike[str]") -> "CommandTool": ...
    def concurrent(self, concurrent: bool) -> "CommandTool": ...

@overload
def tool(func: Callable[..., Any]) -> Callable[..., Any]: ...
@overload
def tool(
    *,
    concurrent: bool = ...,
    paths: Optional[list[str]] = ...,
    schema: Optional[dict] = ...,
    name: Optional[str] = ...,
    description: Optional["str | os.PathLike[str]"] = ...,
) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class Schema:
    def __init__(self, document: Any) -> None: ...
    def validate(self, value: Any) -> tuple[Any, list[str]]: ...

class SchemaStore:
    def __init__(self) -> None: ...
    def label(self, label: str, document: Any) -> "SchemaStore": ...
    def get(self, label: str) -> Optional[Schema]: ...

class ReplyContent:
    """One block inside a reply: text, a tool call, a tool result, or reasoning."""

    @staticmethod
    def text(text: str) -> "ReplyContent": ...
    @staticmethod
    def tool_use(id: str, name: str, input: Any) -> "ReplyContent": ...
    @staticmethod
    def tool_result(
        tool_use_id: str,
        content: str,
        succeeded: bool = ...,
        path: Optional[str] = ...,
    ) -> "ReplyContent": ...
    @staticmethod
    def thinking(thinking: str, signature: str) -> "ReplyContent": ...
    @staticmethod
    def redacted_thinking(data: str) -> "ReplyContent": ...
    def get_kind(self) -> str: ...
    def get_data(self) -> dict: ...
    def __repr__(self) -> str: ...

class Reply:
    """One entry in a task's replies."""

    @staticmethod
    def user_text(text: str) -> "Reply": ...
    def get_author(self) -> str: ...
    def get_content(self) -> list[ReplyContent]: ...
    def get_created_at(self) -> int: ...
    def __repr__(self) -> str: ...

class Query:
    """Selects tasks or recorded events by field values, compiled from AQL.

    The string is the same syntax a query argument carries, `ORDER BY <field>
    ASC | DESC` included. It is read over the task fields where tasks are
    selected and over the event fields where events are, so one the two field
    sets both reject raises `ValueError` here, and one only the other set
    accepts raises where it is used.
    """

    def __init__(self, query: str) -> None: ...
    def __repr__(self) -> str: ...

class Task:
    def __init__(
        self,
        task: Any,
        *,
        label: Optional[str] = ...,
        schema: Optional[Schema] = ...,
        parent: Optional[str] = ...,
    ) -> None: ...
    def get_id(self) -> str: ...
    def get_status(self) -> str: ...
    def get_task(self) -> Any: ...
    def get_result(self) -> Optional[Any]: ...
    def get_label(self) -> Optional[str]: ...
    def get_schema(self) -> Optional[Schema]: ...
    def get_parent(self) -> Optional[str]: ...
    def get_reporter(self) -> str: ...
    def get_assignee(self) -> Optional[str]: ...
    def get_created_at(self) -> int: ...
    def get_started_at(self) -> Optional[int]: ...
    def get_finished_at(self) -> Optional[int]: ...
    def get_failed_at(self) -> Optional[int]: ...
    def get_replies(self) -> list[Reply]: ...
    def get_errors(self) -> list[Event]: ...
    def is_todo(self) -> bool: ...
    def is_finished(self) -> bool: ...
    def is_failed(self) -> bool: ...
    def is_in_progress(self) -> bool: ...
    def is_pending(self) -> bool: ...
    def is_cancelled(self) -> bool: ...
    def __repr__(self) -> str: ...

class Trajectory:
    @staticmethod
    def from_task(
        agent_id: str, model: Optional[str], task: Task
    ) -> "Trajectory": ...
    def save(self, dir: str) -> None: ...
    def get_id(self) -> str: ...
    def get_model(self) -> Optional[str]: ...
    def get_replies(self) -> list[Reply]: ...
    def __repr__(self) -> str: ...

class Page:
    def __init__(
        self,
        slug: str,
        description: str,
        content: str,
        kind: str = ...,
        tags: Optional[list[str]] = ...,
    ) -> None: ...
    def get_slug(self) -> str: ...
    def get_kind(self) -> str: ...
    def get_description(self) -> str: ...
    def get_content(self) -> str: ...
    def get_tags(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class Pages:
    def save(self, page: Page) -> None: ...
    def get_page(self, slug: str) -> Page: ...
    def get_pages(self) -> list[Page]: ...
    def remove(self, slug: str) -> None: ...

class Knowledge:
    @staticmethod
    def load(store_dir: str) -> "Knowledge": ...
    def set_char_limit(self, count: int) -> "Knowledge": ...
    def get_index_char_limit(self) -> int: ...
    def get_index(self) -> str: ...
    def get_pages(self) -> Pages: ...
    def clear(self) -> None: ...

class Event:
    RUN_STARTED: str
    RUN_FINISHED: str
    TASK_CREATED: str
    TASK_STARTED: str
    TASK_FINISHED: str
    TASK_FAILED: str
    TURN_STARTED: str
    REQUEST_STARTED: str
    REQUEST_FINISHED: str
    REQUEST_FAILED: str
    REQUEST_RETRIED: str
    TEXT_CHUNK_RECEIVED: str
    TOOL_CALL_REPAIRED: str
    TOOL_CALL_DECLINED: str
    TOOL_CALL_STARTED: str
    TOOL_CALL_FINISHED: str
    TOOL_CALL_FAILED: str
    FILE_OPEN_FINISHED: str
    FILE_OPEN_FAILED: str
    KNOWLEDGE_WRITTEN: str
    KNOWLEDGE_READ: str
    KNOWLEDGE_REMOVED: str
    KNOWLEDGE_LISTED: str
    KNOWLEDGE_FAILED: str
    POLICY_VIOLATED: str
    SCHEMA_RETRIED: str
    COMPACTION_STARTED: str
    COMPACTION_PROGRESS: str
    COMPACTION_FINISHED: str
    COMPACTION_FAILED: str
    def __init__(self, name: str) -> None: ...
    def data(self, data: Any) -> "Event": ...
    def directive(self, directive: str) -> "Event": ...
    def task_id(self, task_id: str) -> "Event": ...
    def agent_id(self, agent_id: str) -> "Event": ...
    def get_name(self) -> str: ...
    def get_directive(self) -> Optional[str]: ...
    def get_data(self) -> Any: ...
    def get_task_id(self) -> str: ...
    def get_agent_id(self) -> str: ...
    def get_label(self) -> Optional[str]: ...
    def get_created_at(self) -> int: ...
    def __repr__(self) -> str: ...

class Directive:
    """Every directive agentwerk can send, one constant per key."""

    REPLY_REJECTED: str
    NO_TOOL_CALLED: str
    ARGUMENTS_REJECTED: str
    ARGUMENTS_EXPECTED: str
    RESULT_SCHEMA_REQUIRED: str
    SUMMARY_REQUESTED: str
    KNOWLEDGE_INDEX_TRUNCATED: str
    TOOL_NOT_FOUND: str
    NO_TOOLS_REGISTERED: str
    TOOL_PANICKED: str
    TOOL_OUTPUT_EMPTY: str
    TOOL_OUTPUT_OFFLOADED: str
    EDIT_FILE_READ_FAILED: str
    EDIT_FILE_OLD_STRING_NOT_FOUND: str
    EDIT_FILE_OLD_STRING_NOT_UNIQUE: str
    EDIT_FILE_WRITE_FAILED: str
    WRITE_FILE_PARENT_NOT_CREATED: str
    WRITE_FILE_FAILED: str
    READ_FILE_PATH_IS_DIRECTORY: str
    READ_FILE_PATH_IS_DIRECTORY_WITH_ENTRIES: str
    READ_FILE_IS_BINARY: str
    READ_FILE_NOT_FOUND: str
    READ_FILE_FAILED: str
    LIST_DIRECTORY_PATH_IS_FILE: str
    LIST_DIRECTORY_NOT_FOUND: str
    LIST_DIRECTORY_FAILED: str
    PATH_HINT_DIRECTORY_LISTED: str
    PATH_HINT_SUGGESTION: str
    PATH_HINT_WORKING_DIRECTORY: str
    COMMAND_CANCELLED: str
    COMMAND_TIMED_OUT: str
    COMMAND_NOT_STARTED: str
    COMMAND_MISSING: str
    COMMAND_SHELL_OPERATOR_FOUND: str
    COMMAND_QUOTE_UNTERMINATED: str
    COMMAND_CONTROL_CHARACTER_FOUND: str
    COMMAND_ASSIGNMENT_FOUND: str
    COMMAND_FLAG_DENIED: str
    COMMAND_PATTERN_DENIED: str
    COMMAND_NOT_ALLOWED: str
    COMMAND_FLAG_NOT_ALLOWED: str
    GREP_CANCELLED: str
    GREP_TIMED_OUT: str
    GREP_FAILED: str
    GREP_GLOB_REJECTED: str
    GREP_FILE_TYPE_UNKNOWN: str
    GREP_PATTERN_REJECTED: str
    CODE_PATTERN_REJECTED: str
    CODE_CONSTRAINT_INCOMPLETE: str
    CODE_CONSTRAINT_METAVARIABLE_UNKNOWN: str
    CODE_CONSTRAINT_REGEX_REJECTED: str
    FETCH_URL_TOO_LONG: str
    FETCH_URL_SCHEME_MISSING: str
    FETCH_URL_SCHEME_UNSUPPORTED: str
    FETCH_URL_CREDENTIALS_PRESENT: str
    FETCH_URL_HOST_MISSING: str
    FETCH_URL_HOST_NOT_RESOLVABLE: str
    FETCH_URL_TOO_MANY_REDIRECTS: str
    FETCH_URL_REQUEST_FAILED: str
    FETCH_URL_BODY_NOT_READ: str
    FETCH_URL_RESPONSE_TOO_LARGE: str
    FETCH_URL_REDIRECT_LOCATION_MISSING: str
    KNOWLEDGE_PAGE_NOT_FOUND: str
    KNOWLEDGE_WRITE_FAILED: str
    KNOWLEDGE_REMOVE_FAILED: str
    QUEUE_UNAVAILABLE: str
    TASK_ID_MISSING: str
    TASK_NOT_ASSIGNED: str
    TASK_NOT_FOUND: str
    TASK_RESULT_MISSING: str
    TASK_QUERY_INVALID: str
    TASK_EDIT_INCOMPLETE: str
    TASK_TRANSITION_REJECTED: str
    HANDOVER_RESULT_MISSING: str
    FINISH_ARGUMENT_BLANK: str
    SCHEMA_FALSE_REJECTED: str
    SCHEMA_TYPE_MISMATCHED: str
    SCHEMA_CONST_MISMATCHED: str
    SCHEMA_ENUM_MISMATCHED: str
    SCHEMA_ANY_OF_UNMATCHED: str
    SCHEMA_ONE_OF_AMBIGUOUS: str
    SCHEMA_NOT_MATCHED: str
    SCHEMA_PROPERTY_MISSING: str
    SCHEMA_PROPERTY_UNEXPECTED: str
    SCHEMA_ARRAY_TOO_SHORT: str
    SCHEMA_ARRAY_TOO_LONG: str
    SCHEMA_STRING_TOO_SHORT: str
    SCHEMA_STRING_TOO_LONG: str
    SCHEMA_PATTERN_UNMATCHED: str
    SCHEMA_NUMBER_TOO_SMALL: str
    SCHEMA_NUMBER_TOO_LARGE: str
    SCHEMA_HINT_UNQUOTE: str
    SCHEMA_HINT_JSON: str
    SCHEMA_HINT_QUOTE: str

class Agent:
    """The core entity of agentwerk. It has access to tools for solving tasks in
    the form of tasks."""

    def __init__(self) -> None: ...
    @staticmethod
    def from_env() -> "Agent": ...
    def provider(self, provider: Provider) -> "Agent": ...
    def model(self, model: "str | Model") -> "Agent": ...
    def role(self, role: "str | os.PathLike[str]") -> "Agent": ...
    def label(self, label: str) -> "Agent": ...
    def interactive(self) -> "Agent": ...
    def template(self, key: str, value: str) -> "Agent": ...
    def templates(self, variables: dict[str, str]) -> "Agent": ...
    def dir(self, dir: str) -> "Agent": ...
    def knowledge(self, store: Knowledge) -> "Agent": ...
    def directives(self, compute: Callable[[str], Optional[str]]) -> "Agent": ...
    def tool(self, tool: Any) -> "Agent": ...
    def tools(self, tools: list) -> "Agent": ...
    def get_id(self) -> str: ...
    def task(self, task: "Task | Any") -> str: ...
    def start(self) -> "Queue": ...

class Policy:
    max_turns: Optional[int]
    max_input_tokens: Optional[int]
    max_output_tokens: Optional[int]
    max_request_tokens: Optional[int]
    max_schema_retries: Optional[int]
    max_request_retries: int
    request_retry_delay: float
    max_time: Optional[float]
    compaction_threshold: Optional[float]

    def __init__(
        self,
        *,
        max_turns: Optional[int] = ...,
        max_input_tokens: Optional[int] = ...,
        max_output_tokens: Optional[int] = ...,
        max_request_tokens: Optional[int] = ...,
        max_schema_retries: Optional[int] = ...,
        max_request_retries: Optional[int] = ...,
        request_retry_delay: Optional[float] = ...,
        max_time: Optional[float] = ...,
        compaction_threshold: Optional[float] = ...,
    ) -> None: ...

class Queue:
    def __init__(self) -> None: ...
    @staticmethod
    def load(tasks_dir: str) -> "Queue": ...
    def set_policy(self, policy: "Policy") -> "Queue": ...
    def get_policy(self) -> "Policy": ...
    def set_dir(self, dir: str) -> "Queue": ...
    def get_dir(self) -> str: ...
    def set_schemas(self, store: SchemaStore) -> "Queue": ...
    def add_agent(self, agent: Agent) -> "Queue": ...
    def add_task(self, task: "Task | Any") -> str: ...
    def add_reply(self, id: str, content: str) -> "Queue": ...
    def emit_event(self, event: Event) -> Event: ...
    def edit_replies(
        self, id: str, editor: Callable[[list[Reply]], Optional[list[Reply]]]
    ) -> "Queue": ...
    def set_task_finished(self, id: str, result: Any) -> None: ...
    def set_task_failed(self, id: str) -> None: ...
    def on_event(
        self, handler: Callable[["Queue", Event], Any]
    ) -> "Queue": ...
    def on_event_async(
        self, handler: Callable[["Queue", Event], Awaitable[Any]]
    ) -> "Queue": ...
    def on_result(
        self, handler: Callable[["Queue", Task, Any], Any]
    ) -> "Queue": ...
    def on_result_async(
        self, handler: Callable[["Queue", Task, Any], Awaitable[Any]]
    ) -> "Queue": ...
    def on_failure(
        self, handler: Callable[["Queue", Event, Task], Any]
    ) -> "Queue": ...
    def on_failure_async(
        self, handler: Callable[["Queue", Event, Task], Awaitable[Any]]
    ) -> "Queue": ...
    def on_task(
        self, handler: Callable[["Queue", Event, Task], Any]
    ) -> "Queue": ...
    def on_task_async(
        self, handler: Callable[["Queue", Event, Task], Awaitable[Any]]
    ) -> "Queue": ...
    def start(self) -> "Queue": ...
    async def finish_result(
        self, matches: "Query | str | Callable[[Task], bool]"
    ) -> Optional[Any]: ...
    async def finish_results(
        self, matches: "Query | str | Callable[[Task], bool]"
    ) -> list[Any]: ...
    async def finish_all_tasks(self) -> list[Any]: ...
    def cancel_tasks(
        self, matches: "Query | str | Callable[[Task], bool]"
    ) -> "Queue": ...
    def cancel_all_tasks(self) -> "Queue": ...
    def get_task(self, id: str) -> Optional[Task]: ...
    def get_tasks(self) -> list[Task]: ...
    def find_task(
        self, predicate: "Query | str | Callable[[Task], bool]"
    ) -> Optional[Task]: ...
    def find_tasks(
        self, predicate: "Query | str | Callable[[Task], bool]"
    ) -> list[Task]: ...
    def get_results(self) -> list[Any]: ...
    def find_result(
        self, query: "Query | str | Callable[[Task], bool]"
    ) -> Optional[Any]: ...
    def find_results(
        self, query: "Query | str | Callable[[Task], bool]"
    ) -> list[Any]: ...
    def find_event(
        self, matches: "Query | str | Callable[[Event], bool]"
    ) -> Optional[Event]: ...
    def find_events(
        self, matches: "Query | str | Callable[[Event], bool]"
    ) -> list[Event]: ...
    def get_finish_reason(self) -> Optional[str]: ...
    def get_model_for_agent(self, agent_id: str) -> Optional[str]: ...
    def get_input_tokens(self) -> int: ...
    def get_output_tokens(self) -> int: ...
    def get_duration(self) -> Optional[float]: ...
